version: '3.7'
services:
    ### MySQL ################################################
    mariadb:
        container_name: mariadb
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_HOST: localhost
        ports:
            - 3306:3306
        entrypoint:
            sh -c "
            echo 'CREATE DATABASE IF NOT EXISTS autoimport;' > /docker-entrypoint-initdb.d/init.sql;
            /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
            "
        volumes:
            - ./mariadb:/var/lib/mysql/
        networks:
            - elknetwork

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - 82:80
        environment:
            PMA_USER: root
            PMA_PASSWORD: root
            PMA_HOST: mariadb
        depends_on:
            - mariadb
        networks:
            - elknetwork

    ## php ####~###########################################
    php:
        build: ./php-fpm
        networks:
            - elknetwork
        ports:
            - "9000:9001"
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
        links:
            - mariadb
        extra_hosts:
            - "docker-host.localhost:127.0.0.1"

    ## nginx ##############################################
    nginx:
        build: ./nginx
        networks:
            - elknetwork
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ./symfony:/var/www/symfony:cached

    ## ElasticSearch logstash###############################
    elk:
        image: willdurand/elk
        networks:
            - elknetwork
        ports:
            - "81:80"
        volumes:
            - ./elk/logstash:/etc/logstash:cached
            - ./elk/logstash/patterns:/opt/logstash/patterns:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
            - ./logs/nginx:/var/log/nginx:cached
networks:
    elknetwork:
        driver: bridge